//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomControls.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Change log finename. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgChangeLogFile {
            get {
                return ResourceManager.GetString("MsgChangeLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Still not proccessed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDefaultProcessMessage {
            get {
                return ResourceManager.GetString("MsgDefaultProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is supported on the current platform. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgErrUnsupported {
            get {
                return ResourceManager.GetString("MsgErrUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgOk {
            get {
                return ResourceManager.GetString("MsgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBCancel {
            get {
                return ResourceManager.GetString("TxtBCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBClear {
            get {
                return ResourceManager.GetString("TxtBClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBExit {
            get {
                return ResourceManager.GetString("TxtBExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBRefresh {
            get {
                return ResourceManager.GetString("TxtBRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBSave {
            get {
                return ResourceManager.GetString("TxtBSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUILD DATE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBuildDate {
            get {
                return ResourceManager.GetString("TxtBuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtBVersion {
            get {
                return ResourceManager.GetString("TxtBVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtDetailsCollapsedLabel {
            get {
                return ResourceManager.GetString("TxtDetailsCollapsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invisible details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtDetailsExpandedLabel {
            get {
                return ResourceManager.GetString("TxtDetailsExpandedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtHeader {
            get {
                return ResourceManager.GetString("TxtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unlock administrator mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtHUnlock {
            get {
                return ResourceManager.GetString("TxtHUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE input a passcode of administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtInputPasscode {
            get {
                return ResourceManager.GetString("TxtInputPasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtLog {
            get {
                return ResourceManager.GetString("TxtLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtMFile {
            get {
                return ResourceManager.GetString("TxtMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtMHelp {
            get {
                return ResourceManager.GetString("TxtMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtMTool {
            get {
                return ResourceManager.GetString("TxtMTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtRemainingTime {
            get {
                return ResourceManager.GetString("TxtRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unlocked DEBUGGER MODE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtSuccessUnlock {
            get {
                return ResourceManager.GetString("TxtSuccessUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VERSION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TxtVersion {
            get {
                return ResourceManager.GetString("TxtVersion", resourceCulture);
            }
        }
    }
}
